export const TYPES = {
  FETCH_DAYS: "FETCH_DATA",
  FETCH_DATA_SUCCESS: "FETCH_DATA_OK",
  FETCH_SESSIONS: "FETCH_SESSIONS",
  FETCH_SESSIONS_SUCCESS: "FETCH_SESSIONS_SUCCESS",
  FETCH_PLACES: "FETCH_PLACES",
  FETCH_PLACES_SUCCESS: "FETCH_PLACES_SUCCESS",
  GET_SESSION_ID: "GET_SESSION_ID",
  BOOKED_PLACE: "BOOKED_PLACE",
  PUT_PLACES: "PUT_PLACES",
  PUT: "PUT",
};
