export const TYPES = {
  FETCH_DAYS: "FETCH_DATA",
  FETCH_DATA_SUCCESS: "FETCH_DATA_OK",
  FETCH_SESSIONS: "FETCH_SESSIONS",
  FETCH_SESSIONS_SUCCESS: "FETCH_SESSIONS",
  GET_SESSION_ID: "GET_SESSION_ID",
  FETCH_PLACES: "FETCH_PLACES",
};
